# coding: utf-8
# Arquivo template de configuracao
# do vagrant para teste de modulos do puppet.
# Autor: leonardo.rmello@dataprev.gov.br
#
# CONFIGURACAO DE VARIAVEIS

# Domínio dos servidores
DOMAIN="prevnet"

# Normalmente esta memória é mais do que suficiente.
MEMORY=500


Vagrant.configure("2") do |config|

  ##################
  # REDHAT 7.0    #
  ##################
  config.vm.define "webhook-redhat-70" do |v|
    # Configura detalhes da maquina virtual
    v.vm.box = "redhat-70-x64-vbox4210-dtp"
    v.vm.box_url = "http://nfs.prj.configdtp/vagrant-boxes/redhat-70-x64-vbox4210-dtp.box"
    v.vm.host_name = "webhook-redhat-70-vagrant.#{DOMAIN}"
    # FORWARD (forwarded_port) => para acesso no host via http://localhost:8080
    v.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
    # Configura atributos do Virtualbox.
    v.vm.provider "virtualbox" do |virtualbox|
      virtualbox.name = "webhook-redhat-70-vagrant"
      virtualbox.memory = MEMORY
      virtualbox.cpus = 1
    end
    # Configura o puppet como provider
    v.vm.provision :puppet, :options => ["--pluginsync"], :module_path => "modules" do |puppet|
      puppet.manifests_path = "./"
      puppet.manifest_file = "site.pp"
      puppet.options = "--environment dev --verbose"
      puppet.hiera_config_path = "hiera.yaml"
    end
  end

###FIM DO ARQUIVO
end
